#if !canImport(ObjectiveC)
import XCTest

extension SingleStateStateMachineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SingleStateStateMachineTests = [
        ("testCancelAllEffects", testCancelAllEffects),
        ("testEffectCanTriggerItself", testEffectCanTriggerItself),
        ("testSingleStateStateMachine", testSingleStateStateMachine),
        ("testTriggerEffectTwiceAtSameTime", testTriggerEffectTwiceAtSameTime),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SingleStateStateMachineTests.__allTests__SingleStateStateMachineTests),
    ]
}
#endif
