#if !canImport(ObjectiveC)
import XCTest

extension SensorUnitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SensorUnitTests = [
        ("testTrivialStateMachine", testTrivialStateMachine),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SensorUnitTests.__allTests__SensorUnitTests),
    ]
}
#endif
