#if !canImport(ObjectiveC)
import XCTest

extension AssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionTests = [
        ("testArraySeveralElementsTimeline", testArraySeveralElementsTimeline),
        ("testArraySingleElementTimeline", testArraySingleElementTimeline),
        ("testCompletionSuccess", testCompletionSuccess),
        ("testCompletionWithEventSuccess", testCompletionWithEventSuccess),
        ("testDifferentLengthTimeline", testDifferentLengthTimeline),
        ("testDifferentObjectSubValue", testDifferentObjectSubValue),
        ("testDifferentSubSubValue", testDifferentSubSubValue),
        ("testDifferentSubSubValue2", testDifferentSubSubValue2),
        ("testDifferentSubSubValueWithCustomDescription", testDifferentSubSubValueWithCustomDescription),
        ("testDifferentSubValue", testDifferentSubValue),
        ("testDifferentSubValue2", testDifferentSubValue2),
        ("testDifferentSubValueAndTimeline", testDifferentSubValueAndTimeline),
        ("testDifferentValue", testDifferentValue),
        ("testDifferentValueWithWhiteSpace", testDifferentValueWithWhiteSpace),
        ("testEnumDifferentCases", testEnumDifferentCases),
        ("testEnumDifferentComplexSubvalues1", testEnumDifferentComplexSubvalues1),
        ("testEnumDifferentComplexSubvalues2", testEnumDifferentComplexSubvalues2),
        ("testEnumDifferentSubvalues", testEnumDifferentSubvalues),
        ("testEnumDifferentSubvalues2", testEnumDifferentSubvalues2),
        ("testEnumEqualSeveralSubvalues", testEnumEqualSeveralSubvalues),
        ("testEnumSameComplexSubvalues", testEnumSameComplexSubvalues),
        ("testErrorWithEventSuccess", testErrorWithEventSuccess),
        ("testMissingCompletion", testMissingCompletion),
        ("testMissingCompletionWithEvent", testMissingCompletionWithEvent),
        ("testMissingError", testMissingError),
        ("testMissingErrorWithEvent", testMissingErrorWithEvent),
        ("testMissingEvents", testMissingEvents),
        ("testMissingUnknownError", testMissingUnknownError),
        ("testMissingUnknownErrorWithEvent", testMissingUnknownErrorWithEvent),
        ("testOptionalNilTimelineAssertionSuccessful", testOptionalNilTimelineAssertionSuccessful),
        ("testOptionalTimeline", testOptionalTimeline),
        ("testOptionalValueTimelineAssertionSuccessful", testOptionalValueTimelineAssertionSuccessful),
        ("testSameTimelineDifferentEventNames", testSameTimelineDifferentEventNames),
        ("testSetSeveralElementsTimeline", testSetSeveralElementsTimeline),
        ("testSetSeveralElementsTimelineAssertionSuccessful", testSetSeveralElementsTimelineAssertionSuccessful),
        ("testSetSingleElementTimeline", testSetSingleElementTimeline),
        ("testSeveralEventsSameTimeAssertionSuccessful", testSeveralEventsSameTimeAssertionSuccessful),
        ("testSeveralEventsSameTimeDifferentEvents", testSeveralEventsSameTimeDifferentEvents),
        ("testSeveralEventsSameTimeMissingEvent", testSeveralEventsSameTimeMissingEvent),
        ("testSeveralEventsSameTimeSeveralGroupsAssertionSuccessful", testSeveralEventsSameTimeSeveralGroupsAssertionSuccessful),
        ("testSeveralEventsSameTimeSeveralGroupsMissingElement", testSeveralEventsSameTimeSeveralGroupsMissingElement),
        ("testSeveralEventsSameTimeUnexpectedEvent", testSeveralEventsSameTimeUnexpectedEvent),
        ("testUnexpectedCompletion", testUnexpectedCompletion),
        ("testUnexpectedCompletionWithEvent", testUnexpectedCompletionWithEvent),
        ("testUnexpectedError", testUnexpectedError),
        ("testUnexpectedErrorWithEvent", testUnexpectedErrorWithEvent),
        ("testUnexpectedEvents", testUnexpectedEvents),
        ("testUnexpectedUnknownError", testUnexpectedUnknownError),
        ("testUnexpectedUnknownErrorWithEvent", testUnexpectedUnknownErrorWithEvent),
        ("testUnknownErrorMatchesAnyError", testUnknownErrorMatchesAnyError),
        ("testUnknownErrorMatchesAnyErrorWithOtherEvents", testUnknownErrorMatchesAnyErrorWithOtherEvents),
        ("testUnknownErrorSuccess", testUnknownErrorSuccess),
        ("testUnkownErrorWithEventSuccess", testUnkownErrorWithEventSuccess),
    ]
}

extension RandomAssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomAssertionTests = [
        ("testRandomTimeline", testRandomTimeline),
    ]
}

extension TimelineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TimelineTests = [
        ("testCompleted", testCompleted),
        ("testEmptyTimeline", testEmptyTimeline),
        ("testError", testError),
        ("testUnkownError", testUnkownError),
        ("testValues", testValues),
        ("testValuesAtSameTime", testValuesAtSameTime),
        ("testValuesAtSameTimeWithCompletion", testValuesAtSameTimeWithCompletion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AssertionTests.__allTests__AssertionTests),
        testCase(RandomAssertionTests.__allTests__RandomAssertionTests),
        testCase(TimelineTests.__allTests__TimelineTests),
    ]
}
#endif
