#if !canImport(ObjectiveC)
import XCTest

extension AssertionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AssertionTests = [
        ("testDifferentLengthTimeline", testDifferentLengthTimeline),
        ("testDifferentSubValue", testDifferentSubValue),
        ("testDifferentSubValueAndTimeline", testDifferentSubValueAndTimeline),
        ("testDifferentValue", testDifferentValue),
        ("testMissingEvents", testMissingEvents),
        ("testSameTimelineDifferentEventNames", testSameTimelineDifferentEventNames),
        ("testUnexpectedEvents", testUnexpectedEvents),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AssertionTests.__allTests__AssertionTests),
    ]
}
#endif
